### DISCUSSION TITLE
Set up for simple use.

### DISCUSSION THREAD

**Discussion by sitenzo** [alstr/todo-to-issue-action#174] [Q&A] [answered]
Hi All,

I have created a workflow `todo.yml` workflow

```yml
name: "Run TODO to Issue"
on: [ "push" ]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v4"
        id: "todo"

```

After this i created a todo in my project file (.php)

```php
        // todo: Send dynamic Welcome Mail to Users
        // This needs to be dynamic, admins need to manage welcome mail text and lay-out.
```

The action is running but there is no issue created.
Even if i try different formats of todo like

```php
// @todo test1
// todo: test2
/*
 * todo: test3
 */ 
```

How can i investigate this further and so it will create issues for me on Github?

This is a public repo https://github.com/sitenzo/test-todo

I think i need to change some configuration but don't know witch one for this to work.

Thanks for the help
