### ISSUE TITLE
For some reason, issues are created twice?

### ISSUE THREAD

**Issue by camposcristianeze** [alstr/todo-to-issue-action#10]
This is my current workflow.

Thanks!

```
# This is a basic workflow to help you get started with Actions

name: TODO's to issues

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master, staging ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@master"
        with:
          REPO: ${{ github.repository }}
          BEFORE: ${{ github.event.before }}
          SHA: ${{ github.sha }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL: "@todo"
          COMMENT_MARKER: "@"
        id: "todo"
```

**Comment by alstr** [comment]
Hey Cristian. 👋

Thanks for the report. I've just done a quick test and I can't reproduce this. Would you be able to share logs?

Workflow events do potentially encompass several activities, which might lead to them running more than once. This page outlines the activities that trigger each event: https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request

You may want to use the `types` keyword to narrow down the events, as described here: https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onevent_nametypes

For example:

```
on:
  release:
    # Only use the types keyword to narrow down the activity types that will trigger your workflow.
    types: [published, created, edited]
```

Also, I notice your workflow file says `Triggers the workflow on push or pull request`, but you've only set it to run on `pull_request` - is that intentional?
