### ISSUE TITLE
No issues for nestjs

### ISSUE THREAD

**Issue by bouteillerAlan** [alstr/todo-to-issue-action#12]
## config
- nestjs project (typescript)
- node v13.10.1
- yarn v1.22.4

## Step to reproduce
- install nestjs
- add some todo in the code
```ts
/** updated password bcrypt */
if (updatedUser.password) {
  // todo bcrypt password
}
```
- run action
- action is done correctly
- no issues is created

## My `.yml` 

```yml
name: Todo to issue

on:
  push:
    branche:
      - '*'

jobs:
  todo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: 'TODO to issue'
        uses: alstr/todo-to-issue-action@v1.2-beta
        with:
          REPO: ${{ github.repository }}
          BEFORE: ${{ github.event.before }}
          SHA: ${{ github.sha }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL: '// todo'
          COMMENT_MARKER: '//'
        id: 'todo'

```

If you need more information please tell me.
