### ISSUE TITLE
Bug: Workflow validation fails because optional inputs are set to required.

### ISSUE THREAD

**Issue by sammcj** [alstr/todo-to-issue-action#125]
Because a number of the inputs are set to required: true, workflow validation fails if they're not provided.

```yaml
  BEFORE:
    description: 'The SHA of the last pushed commit (automatically set)'
    required: true
    default: '${{ github.event.before || github.base_ref }}'
```

You can see here that all required inputs must be provided, and one that I haven't provided fails validation:

![image](https://user-images.githubusercontent.com/862951/195006984-76609d76-49a0-47b8-852b-b1ddd83e7dda.png)

What I would suggest is changing those inputs to required: false, and make the code handle the defaults.
