### ISSUE TITLE
Unexpected input(s) 'IDENTIFIERS'

### ISSUE THREAD

**Issue by vis97c** [alstr/todo-to-issue-action#127]
When running the action using IDENTIFIERS I get this: 
![image](https://user-images.githubusercontent.com/45251845/196064825-7c90f0fb-92dc-4786-9fb4-cb79e61bdd25.png)

My setup:
```yaml
name: "Issues from todo"

on:
    push:
        branches: [dev]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: "TODO to Issue"
              id: "todo"
              uses: "alstr/todo-to-issue-action@v4.6.6"
              with:
                  IDENTIFIERS: |
                      [
                          { "name": "TODO", "labels": ["todo"] },
                          { "name": "REFACTOR", "labels": ["todo"] },
                          { "name": "SUGGESTION", "labels": ["suggestion"] },
                          { "name": "IMPROVEMENT", "labels": ["enhancement"] },
                          { "name": "ENHANCEMENT", "labels": ["enhancement"] },
                      ]

```
