### ISSUE TITLE
"Project does not exist, skipping" when attempting to assign an issue to a project

### ISSUE THREAD

**Issue by devin-helio** [alstr/todo-to-issue-action#152]
Hello,

When adding the org information to a TODO, the action tells me it can't find the project.  Here's what I've tried:

```
// by project id
// TODO: test2
//  org projects: orgname/1/Backlog
```
```
// by project name
// TODO: test2
//  org projects: orgname/project name/Backlog
```
Example response/output from the workflow run:
```
Processing issue 1 of 2
Adding issue to org project 1 of 1
Project does not exist, skipping
Issue created
Processing issue 2 of 2
Issue closed
```

action configuration:
```
    steps:
      # ...
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v4.10.1"
        id: "todo"
        with:
          PROJECTS_SECRET: ${{ secrets.PROJECTS_SECRET }}
```

My PAT has both `repo` and `workflow` access granted to it.  The project is private so I'm not sure how that factors in to things, but I'm not sure what else to try at this point.  Thank you in advance.
