### ISSUE TITLE
action workflow runs but no issue is created

### ISSUE THREAD

**Issue by amine-ammor** [alstr/todo-to-issue-action#158]
Hello, 

I created a test repository to test for the gitub action : https://github.com/amine-ammor/test_repo_for_github_action .

The github action runs but no issue is created. I created and assigned the "secret" to the workflow (with a token with full access with full access), but no issue is created.

Here is the content of the yml file : 
```
name: "Run TODO to Issue"
on: ["push"]
jobs:
    build:
        runs-on: "ubuntu-latest"
        steps:
            - uses: "actions/checkout@v3"
            - name: "TODO to Issue"
              uses: "alstr/todo-to-issue-action@v4"
              with:  
                    PROJECTS_SECRET: ${{ secrets.PROJECTS_SECRET }} 
```

Any idea , where this might come from ?
Should a project exists in  the repository in order for the issue to be created ?
Thank you.
