### ISSUE TITLE
Action ran fine, but didn't pick TSX comments?

### ISSUE THREAD

**Issue by netpoe** [alstr/todo-to-issue-action#160]
So, `.tsx` extension is listed in the languages.yml file, this is my TODO comment:

```
{/*
  @TODO complete the FAQs
  labels: 100 USDT
*/}
```

I already added the `IDENTIFIERS` prop the workflow file: 

```
name: "Run TODO to Issue"
on: ["push"]
jobs:
    build:
        runs-on: "ubuntu-latest"
        steps:
            - uses: "actions/checkout@v3"
            - name: "TODO to Issue"
              uses: "alstr/todo-to-issue-action@v4"
              with:
                IDENTIFIERS: '[{"name": "@TODO", "labels": ["help wanted"]}]'
```

Didn't pick the `@TODO` comment after pushing the file, but the action ran without errors.

Does the comment is formatted incorrectly?
