### ISSUE TITLE
Issues not being closed when the comment is not in the main commit on push

### ISSUE THREAD

**Issue by LouDnl** [alstr/todo-to-issue-action#178]
I have been using this action for a while now and am very pleased with how it works, but am running into some minor things I can't seem to solve.
1. When removal of a comment in the code with one of the identifiers (TODO as example) is pushed to github the issue is automatically closed. But when this commit is part of a larger set of commits issues do not always get closed. It is as if the action only runs on the latest commit of a push? It seems that it is not always this case though, I can't put my finger on it.
2. If you have multiple branches and a pull request is created from one to the other, issues are duplicated.

Action config:
```yaml
  name: "Create issues from TODO and BUG entries"
  on:
    push:
      branches: [ develop ] # develop branch only due to duplicate issues after pull requests on master
  
    workflow_dispatch:
      inputs:
        MANUAL_COMMIT_REF:
          description: "The SHA of the commit to get the diff for"
          required: true
        MANUAL_BASE_REF:
          description: "By default, the commit entered above is compared to the one directly before it; to go back further, enter an earlier SHA here"
          required: false
  jobs:
    managetodos:
      name: Add TODO's and BUGs from code
      runs-on: "ubuntu-latest"
      steps:
        - uses: "actions/checkout@v3"
        - name: "TODO's to Issues"
          uses: "alstr/todo-to-issue-action@master"
          with:
            AUTO_ASSIGN: true
            IDENTIFIERS: '[{"name": "TODO", "labels": ["TODO", "new", "auto generated"]},
                           {"name": "BUG", "labels": ["BUG", "new", "auto generated"]},
                           {"name": "ISSUE", "labels": ["ISSUE", "new", "auto generated"]},
                           {"name": "FIXME", "labels": ["FIXME", "new", "auto generated"]}]'
          env:
            MANUAL_COMMIT_REF: ${{ inputs.MANUAL_COMMIT_REF }}
            MANUAL_BASE_REF: ${{ inputs.MANUAL_BASE_REF }}
```
