### ISSUE TITLE
Exception('Could not retrieve diff. Operation will abort.')

### ISSUE THREAD

**Issue by CermakM** [alstr/todo-to-issue-action#231]
I am hitting [this](https://github.com/alstr/todo-to-issue-action/issues/42) issue with v5 as well, even tho its explicitly stated the `TOKEN` is not required and would default to `github.token`:

```
Traceback (most recent call last):
  File "/app/main.py", line 931, in <module>
    last_diff = StringIO(client.get_last_diff())
                         ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 112, in get_last_diff
    raise Exception('Could not retrieve diff. Operation will abort.')
Exception: Could not retrieve diff. Operation will abort.
```

This is my current configuration:

```
  todo:
    name: Create Issues for code comments
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - uses: actions/checkout@v4
      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v5
        with:
          TOKEN: ${{ github.token }}
          IDENTIFIERS: '[ { "name": "TODO", "labels": [ "todo" ] }, { "name": "FIXME", labels: [ "fixme" ] } ]'
          CLOSE_ISSUES: 'true'
          INSERT_ISSUE_URLS: 'true'
      - name: Set Git user
        run: |
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Commit and Push issue URLS
        run: |
          git add -A
          if [[ `git status --porcelain` ]]; then
            git commit -m "Automatically added GitHub issue links to TODOs"
            git push origin main
          else
            echo "No changes to commit"
          fi
```

I tried adding also `permissions` field but to no affect. My settings are set correctly to allow READ and WRITE. Any idea what' wrong?

**Comment by cmathewsendsight** [comment]
Getting the same issue, config is:

```
name: Create Issue from TODO

on:
    push:
        branches:
            - main
    pull_request:
    workflow_dispatch:
        inputs:
            MANUAL_COMMIT_REF:
                description: 'SHA of the commit to get the diff for'
                required: true
            MANUAL_BASE_REF:
                description: 'Optional: Earlier SHA for comparison'
                required: false

permissions:
    contents: write
    issues: write
    pull-requests: read

jobs:
    create_issue:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Run TODO to Issue Action
              uses: alstr/todo-to-issue-action@v5.1.3
              with:
                  TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CLOSE_ISSUES: false

          
```

Based on logs, repo checks out fine. This is a private repo, but token should be working for access, as it does clone down just fine. I did try it on a separate public repo, and it worked without issue, the exact same format, so I suspect its related to privacy somehow but I'm not sure how.

**Comment by alstr** [comment]
@CermakM @cmathewsendsight Please could you try removing `TOKEN` from your workflow file? The action should have access to the GitHub-supplied token by default, and if you override that with an incorrectly scoped token that may prevent it from working.

**Comment by cmathewsendsight** [comment]
I will try that this morning and report back :)

**Comment by cmathewsendsight** [comment]
Same result

**Comment by alstr** [comment]
In that case I'm not 100% sure. Do you own the private repo? I've tested it on a private repo so it should work with them, but there might be some persmissions issues. You shouldn't need to specify `permissions` in the workflow file for the action to run, so that might be affecting things. I'd also use `@v5` to target the latest v5 release. You could try copying the workflow file from this repository:

```
name: "Run TODO to Issue"
on:
  push:
  workflow_dispatch:
    inputs:
      MANUAL_COMMIT_REF:
        description: "The SHA of the commit to get the diff for"
        required: true
      MANUAL_BASE_REF:
        description: "By default, the commit entered above is compared to the one directly before it; to go back further, enter an earlier SHA here"
        required: false
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@master"
        env:
          MANUAL_COMMIT_REF:
            ${{ inputs.MANUAL_COMMIT_REF }}
          MANUAL_BASE_REF:
            ${{ inputs.MANUAL_BASE_REF }}
```

If none of that works, try creating a classic Personal Access Token with the `repo` scope. Make sure you enter it in `Settings -> Secrets and variables (Actions) -> Secrets`, then reference it by the same name in the workflow file: `SECRET: "${{ secrets.PROJECTS_SECRET }}"`

**Comment by cmathewsendsight** [comment]
Created a new branch, and new PR. This is my action now:

```
name: TODO to Issue revised

on:
    push:
    pull_request:
    workflow_dispatch:
        inputs:
            MANUAL_COMMIT_REF:
                description: 'SHA of the commit to get the diff for'
                required: true
            MANUAL_BASE_REF:
                description: 'Optional: Earlier SHA for comparison'
                required: false

jobs:
    create_issue:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Run TODO to Issue Action
              uses: alstr/todo-to-issue-action@v5
              with:
                  CLOSE_ISSUES: false
```

It succeeds when running against the commit (note, I've removed the branches-`main` check, so now it runs on each commit), but not when running against the PR. The diff/diff URL generated is identical between both runs. I don't see any differences actually in the way either of them are run from the action log, aside from the failure to generate diff message. I think this is probably fine, in that I can just merge and it will probably run properly once its in `main`, but I am still not really sure why it would run against the PR successfully in my test against a public repo, but not against the PR in the private repo. Hopefully that makes sense.

**Comment by maxzitron** [comment]
I'm on the latest version and having the problem running the Action from PR in a Private Repo as well with the same error.
```
Traceback (most recent call last):
  File "/app/main.py", line 162, in <module>
    last_diff = client.get_last_diff()
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/GitHubClient.py", line 90, in get_last_diff
    raise Exception('Could not retrieve diff. Operation will abort.')
Exception: Could not retrieve diff. Operation will abort.
```

Though, my action file is even more simple.

```
on:
  - pull_request

jobs:
  sync-todo-to-issue:
    name: 'Sync TODO to Issue'
    runs-on: 'ubuntu-latest'

    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'TODO to Issue'
        uses: 'alstr/todo-to-issue-action@v5'
```
Hope this provides @alstr a bit more context.
