### ISSUE TITLE
Duplicated issues

### ISSUE THREAD

**Issue by kjetilhp** [alstr/todo-to-issue-action#24]
I'm getting a lot of duplicated issues created, what are the criteria for checking if an issue exist?

I'm not editing the todos but of course the line numbers will change all the time and also filenames will change.

example
```

what? we have to sign in if user have signed in with vipps before!

devent/apps/devent-services/src/app/app.service.ts

Line 70 in 18e42f0

 // TODO: what? we have to sign in if user have signed in with vipps before! 
```
```

what? we have to sign in if user have signed in with vipps before!

devent/apps/devent-services/src/app/app.service.ts

Line 70 in 98b1716

 // TODO: what? we have to sign in if user have signed in with vipps before! 
```

**Comment by alstr** [comment]
Hi, thanks for the report. File names and line numbers shouldn't make a difference.

First it checks the commit diff, to see if the TODO block has been added in that commit. There may be some times where this is a false positive, so it encodes the prospective issue body and checks it against currently open issues in the repo, to check it's not duplicating itself.

https://github.com/alstr/todo-to-issue-action/blob/50ac4cb002099de0a2938ef809f79302d29c821d/main.py#L209

I am not 100% sure on the cause of the issue that you're describing. Is there a hash in the body of each issue? If they are the same it is a duplicate and I don't know why that is. If it's different, there's some underlying difference between the issues that would need looking at closer.

**Comment by kjetilhp** [comment]
hashes are different, 
46cb0548730750214383d5658f8941dcb2c8d4a2
6d7dbb1c820610261d43279d35b1e611f2c8f8f1
..
had to disable the workflow now after 4 duplicates of every todo
![image](https://user-images.githubusercontent.com/393416/97176457-44fe1400-1795-11eb-97b6-8d79a75a7b5c.png)
(I closed all of them manually)
let me know if you want more info on each issue

**Comment by alstr** [comment]
Can you share your `workflow.yaml` configuration? If these are being created on `push`, can you share the sections of the commit/diff?

**Comment by kjetilhp** [comment]
```
name: 'Workflow'
on: ['push']
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@master'
      - name: 'TODO to Issue'
        uses: 'alstr/todo-to-issue-action@v2.0'
        with:
          REPO: ${{ github.repository }}
          BEFORE: ${{ github.event.before }}
          SHA: ${{ github.sha }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL: '// TODO'
          COMMENT_MARKER: '//'
        id: 'todo'

```
