### ISSUE TITLE
Unable to add issue url to the files when setting `INSERT_ISSUE_URLS: True`

### ISSUE THREAD

**Issue by dharmendrasha** [alstr/todo-to-issue-action#252]
when setting `INSERT_ISSUE_URLS: True`

```yaml

name: Create issues from TODOs

on:
  workflow_dispatch:
    inputs:
      MANUAL_COMMIT_REF:
        description: 'The SHA of the commit to get the diff for'
        required: true
      MANUAL_BASE_REF:
        description: 'By default, the commit entered above is compared to the one directly before it; to go back further, enter an earlier SHA here'
        required: false
  pull_request:
  push:
    branches: # TODO: do not set multiple branches, todos might be added and then get referenced by themselves in case of a merge
      - main
#TODO: check works or not
permissions:
  issues: write
  repository-projects: read
  contents: read

jobs:
  todos:
    runs-on: ubuntu-latest

    # TODO: Make sure this work
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          lfs: true
          fetch-depth: 0

      - name: 'TODO to Issue'
        uses: 'alstr/todo-to-issue-action@v5'
        env:
          MANUAL_COMMIT_REF: ${{ inputs.MANUAL_COMMIT_REF }}
          MANUAL_BASE_REF: ${{ inputs.MANUAL_BASE_REF }}
          INSERT_ISSUE_URLS: True

      - name: Set Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Changes
        run: |
          git add -A
          if [[ `git status --porcelain` ]]; then
            git commit -m "Automatically added GitHub issue links to TODOs"
            git push origin main
          else
            echo "No changes to commit"
          fi

```
there is no changes made when enabling this setting to the file
