### ISSUE TITLE
No such file or directory: 'git'

### ISSUE THREAD

**Issue by curxxx** [alstr/todo-to-issue-action#261]
Hi!

I'm trying to run the workflow on a locally hosted Gitea instance and I'm having this issue: 

<img width="896" alt="Image" src="https://github.com/user-attachments/assets/f4cfe16c-e622-4548-b061-789bc39ed9ec" />

I've tried it with 2 different project and got the same result.

```
name: "Run TODO to Issue"
on: "push"

jobs:
  build:
    runs-on: "ubuntu-latest"
    permissions:
      issues: write
    steps:
      - uses: "actions/checkout@v4"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v5"
        with:
          GITHUB_URL: "https://git.lilnas.lan/api/v1"
          PROJECT: "user/Austen/py_shellutils"
          PROJECTS_SECRET: "${{ secrets.PROJECTS_SECRET }}"
```

(And yea, the secret exists and should have full permissions)

<details><summary>Full Log</summary>
<p>

<img width="883" alt="Image" src="https://github.com/user-attachments/assets/e6198105-422b-412e-9c72-fbc3b0bacb48" />

<img width="886" alt="Image" src="https://github.com/user-attachments/assets/54b7b37f-550d-4cba-8c9c-dff761f86f5f" />

</p>
</details>
