### ISSUE TITLE
(feat) add support for ignoring commits matching a message pattern

### ISSUE THREAD

**Issue by vittxr** [alstr/todo-to-issue-action#268]
It would be great to have a similar attribute to `IGNORE`, but specifically for skipping commits that contain a certain string in the message.

It's common to have automated commits for things like dependency updates or linter formatting, where it's not necessary to check for TODOs.

For example, this could be achieved by ignoring commits based on a message prefix pattern. In the case of Dependabot, commit messages typically start with `"Merge pull request"` or `⬆ bump xxxx`

![Image](https://github.com/user-attachments/assets/fc338745-db60-4bdc-a95d-8ad12cda8f0b)

**Comment by alstr** [comment]
Thanks for the feedback. I was wondering if this could be done via the workflow file. I don't think you filter in `on`, but can you exit early if a string is matched?

For example (not tested):

```
name: Filter by Commit Message

on:
  push:

jobs:
  skip-by-message:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest commit message
        id: get_commit
        run: |
          echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT

      - name: Cancel if message contains [SKIP]
        if: contains(steps.get_commit.outputs.message, '[SKIP]')
        run: |
          echo "Skipping job due to commit message"
          exit 0

      - name: Continue with actual job
        run: echo "Running workflow for allowed commit"
```

**Comment by vittxr** [comment]
I'll test it! I didnt know this was possible

**Comment by vittxr** [comment]
used this `yml` file

```yml
name: "Run TODO to Issue"

on: [ "push" ]
jobs:
  build:                    
    runs-on: "ubuntu-latest"
    permissions:
      issues: write
      contents: read
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v4"

      - name: Get latest commit message
        id: get_commit
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "message<<EOF" >> "$GITHUB_OUTPUT"
          echo "$COMMIT_MSG"       >> "$GITHUB_OUTPUT"
          echo "EOF"               >> "$GITHUB_OUTPUT"

      - name: "TODO to Issue"
        if: | 
          !startsWith(steps.get_commit.outputs.message, '⬆ bump') && !startsWith(steps.get_commit.outputs.message, 'Merge pull request')
        uses: "alstr/todo-to-issue-action@v5"
        with:
          CLOSE_ISSUES: true
```

action log for this configuration was:

![Image](https://github.com/user-attachments/assets/da357a51-78a7-4d94-877a-a34a68558efc)

it'd be great avoid pull `alstr/todo-to-issue-action@v5` image too if not needed, but this helped anyway

**Comment by alstr** [comment]
Glad you sorted it. I think you could conditionally exit before the action step runs, if you split up the jobs. So something like:

```
name: "Run TODO to Issue"

on: [ "push" ]

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: Get latest commit message
        id: get_commit
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "message<<EOF" >> "$GITHUB_OUTPUT"
          echo "$COMMIT_MSG" >> "$GITHUB_OUTPUT"
          echo "EOF"          >> "$GITHUB_OUTPUT"

      - name: Check if action should run
        id: check
        run: |
          if [[ "${{ steps.get_commit.outputs.message }}" =~ ^⬆\ bump || "${{ steps.get_commit.outputs.message }}" =~ ^Merge\ pull\ request ]]; then
            echo "should_run=false" >> "$GITHUB_OUTPUT"
          else
            echo "should_run=true" >> "$GITHUB_OUTPUT"
          fi

  todo-to-issue:
    needs: check-commit-message
    if: needs.check-commit-message.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v5"
        with:
          CLOSE_ISSUES: true
```
