### ISSUE TITLE
Only works on the master branch

### ISSUE THREAD

**Issue by GiovanH** [alstr/todo-to-issue-action#28]
Pushing to non-master branches doesn't create any issues. 

Given that the develop branch is where most of my `todo` comments live, since they should be resolved by the time they reach `master`, this seems like a problem.

**Comment by alstr** [comment]
Hey there. Admittedly I haven’t done much testing around this, but have you tried [configuring your `workflow.yml` file to point to a specific branch](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsuses)? Can you share your configuration?

**Comment by weibullguy** [comment]
I can confirm that issues **_can_** be created when pushing to the develop branch.  My partial configuration is below.  I split my workflow files up (one for master, one for develop, one for release branches, one for pull-requests), so the reason it works for me may simply be because the action only lives in my develop workflow file.  However, it should be these lines that cause the action to refer to the develop branch when looking for TODOs:

```
with:
  ref: develop
```

Here's the full configuration for this action in my develop branch workflow file:

```
name: Develop Branch Workflow
 
on:
  push:
    branches: develop

  todo_issue:
    name: Create Issues from Todos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - name: TODO to Issue
        id: todo
        uses: alstr/todo-to-issue-action@v2.0
        with:
          REPO: ${{ github.repository }}
          BEFORE: ${{ github.event.before }}
          SHA: ${{ github.sha }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL: "#// TODO:"
          COMMENT_MARKER: "#//"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by GiovanH** [comment]
This works (once "jobs" is added in):
```yaml
name: "Todo Workflow"
 
on:
  push:
    branches: develop

jobs:
  issues:
    name: Create Issues from Todos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - name: TODO to Issue
        id: todo
        uses: alstr/todo-to-issue-action@v2.0
        with:
          REPO: ${{ github.repository }}
          BEFORE: ${{ github.event.before }}
          SHA: ${{ github.sha }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL: "// TODO:"
          COMMENT_MARKER: "//"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
The key seems to be the explicit
```yaml
      - uses: actions/checkout@v2
        with:
          ref: develop
```

**Comment by alstr** [comment]
Hey. I've just done a bit of testing and I got it to work with the following setup:

```
name: "Workflow"
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v2.3"
        id: "todo"
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Here are some things to bear in mind:

- The first time you commit to the new branch, the action won't pick up any new TODOs because the `BEFORE` input is `0000000000000000000000000000000000000000`. This causes the GitHub API to return a 404 when a diff request is performed. If you plan ahead, it should work on subsequent commits (where `BEFORE` is a valid commit).
- If your TODOs have already been committed and they weren't added by the action for whatever reason (i.e., you added the action afterwards), they won't be picked up by the action later on. This is because it uses the diff file to find TODOs, so they won't get picked up. Theoretically, you could just change a single character and they should be detected.

I'm not 100% sure if there are any better workarounds here yet, but if anyone does have any ideas please do create a new issue!

Hope that helps.
