### ISSUE TITLE
More default values

### ISSUE THREAD

**Issue by robertdebock** [alstr/todo-to-issue-action#29]
Hi,

What a wonderful action, well done!

To ease the installation and improve the readability, I would like a few defaults to be set with these values:

|Variable|Default value|
|---|---|
|REPO|${{ github.repository }}|
|BEFORE|${{ github.event.before }}|
|SHA|${{ github.sha }}|
|TOKEN|${{ secrets.GITHUB_TOKEN }}|
|LABEL|"# TODO"|
|COMMENT_MARKER|"#"|

These can be set by adding the `default` parameter per input parameter. Something like this:

```yaml
inputs:
  REPO:
    description: "The path to the repository where the action will be used, e.g. 'alstr/my-repo' (automatically set)"
    required: true
    default: ${{ github.repository }}
```

And the default setting in main.py can be removed.

What do you think? If you like it, I'll make a proposal and pull request.

Once again, thanks for your work on this, looks promising.
