### ISSUE TITLE
scope of PAT

### ISSUE THREAD

**Issue by tst32** [alstr/todo-to-issue-action#65]
what are the scope of PAT that i need to pass?

**Comment by alstr** [comment]
I would recommend `repo` and `workflow`. You can use the default `GITHUB_TOKEN` and that will work fine, but if you want to customise the permissions you can do so via the [workflow file](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions).

That is for the standard functionality. If you want to enable the projects functionality, that is described [here](https://github.com/alstr/todo-to-issue-action#projects).

**Comment by tst32** [comment]
It seems that i'm mising something in PAT setup
for the moment build fails with ```Traceback (most recent call last):
  File "/app/main.py", line 591, in <module>
    last_diff = StringIO(client.get_last_diff())
  File "/app/main.py", line 72, in get_last_diff
    raise Exception('Could not retrieve diff. Operation will abort.')
Exception: Could not retrieve diff. Operation will abort. ```
I have generated PAT as follow  
![image](https://user-images.githubusercontent.com/23115742/127310412-6234da8f-7f32-4b38-831a-1eaaffb5fd38.png)
![image](https://user-images.githubusercontent.com/23115742/127310591-ab0e0ddd-389f-4ae0-924d-55cee81f5113.png)
it is marked as never used - so am i  wrong with workflow.yml ?
 ```
    name: "Workflow"
    on: ["push"]
    jobs:
      build:
        runs-on: "ubuntu-latest"
        steps:
          - uses: "actions/checkout@master"
          - name: "TODO to Issue"
            uses: "alstr/todo-to-issue-action@v4.0.7"
            id: "todo"
            with:
              TOKEN: ${{ secrets.TODO_SECRET }}
```
