### ISSUE TITLE
Runtime of action

### ISSUE THREAD

**Issue by mbtools** [alstr/todo-to-issue-action#89]
The vast majority of the runtime is consumed by the build step:

![image](https://user-images.githubusercontent.com/59966492/141142382-ed4fae40-efaf-4826-86d5-308aba95b0c2.png)

You can prebuild the Docker image for your action and then in the action.yml file you specify the prebuilt image instead of Dockerfile. See the documentation [here](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-docker-actions).

Something like this

```yml
runs:
  using: 'docker'
  image: 'docker://alstr/todo-to-issue-action:4.4.1'
```

PS: Also nice to use https://github.com/marketplace/actions/docker-hub-description to keep the docker readme in sync with github
